using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WebApplication1.Migrations
{
    /// <inheritdoc />
    public partial class version1114 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "DepuracionExportSiebel1",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CVTipoConexion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CanalDeIngreso = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CMDSCER = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CMUSCER = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoEscenario = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoAdmision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FallaGeneralAsociada = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaAdmision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FD = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nodo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Rama = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RXDS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenSOA = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Segmento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SNRDS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SNRUP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenPedido = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PuntosTecnicos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoCuenta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXUP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ÍnstalacionExpress = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TelefonoPrincipal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Telefonos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoEMTA = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CtaEspecial = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hub = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed27 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenPortabilidad = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Referido = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoCancelacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sistema = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubEstado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NoVTS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaveVendedor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MensalidadTotal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalCNR = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentoPrueba = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoFecha = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoTipoOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Revision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CuentaFacturacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransferidoTrabajoTransacciones = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Equipo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Activo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AplicaTablet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConfirmacionInstalacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaveTecnicoPrincipal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tipo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tipo1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoAsignacionCredito = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed53 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumProgramaciones = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed55 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Estado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Compania = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Centro = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListaImpuestos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Direccion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Apellidos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nombre = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Prioridad = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumCuenta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Aprobado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AprobadoPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Moneda = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListaPrecios = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PorcientoDescuento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CompletadaPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoReprogramacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnviadaPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UltimaModificacionPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UltimaModificacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comentarios = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreadoPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Creado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Evento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaSolicitada = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Organizacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cerrado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed82 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CICPotencial = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DepuracionExportSiebel1", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "depuracionExportSiebelCanceladas1",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CVTipoConexion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CanalDeIngreso = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CMDSCER = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CMUSCER = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoEscenario = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoAdmision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FallaGeneralAsociada = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaAdmision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FD = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nodo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Rama = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RXDS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenSOA = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Segmento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SNRDS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SNRUP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenPedido = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PuntosTecnicos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoCuenta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXUP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ÍnstalacionExpress = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TelefonoPrincipal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Telefonos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoEMTA = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CtaEspecial = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hub = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed27 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenPortabilidad = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Referido = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoCancelacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sistema = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubEstado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NoVTS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaveVendedor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MensalidadTotal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalCNR = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentoPrueba = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoFecha = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoTipoOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Revision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CuentaFacturacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransferidoTrabajoTransacciones = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Equipo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Activo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AplicaTablet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConfirmacionInstalacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaveTecnicoPrincipal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tipo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tipo1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoAsignacionCredito = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed53 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumProgramaciones = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed55 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Estado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Compania = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Centro = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListaImpuestos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Direccion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Apellidos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nombre = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Prioridad = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumCuenta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Aprobado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AprobadoPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Moneda = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListaPrecios = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PorcientoDescuento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CompletadaPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoReprogramacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnviadaPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UltimaModificacionPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UltimaModificacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comentarios = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreadoPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Creado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Evento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaSolicitada = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Organizacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cerrado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed82 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CICPotencial = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_depuracionExportSiebelCanceladas1", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "depuracionExportSiebelReserva1",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CVTipoConexion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CanalDeIngreso = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CMDSCER = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CMUSCER = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoEscenario = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoAdmision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FallaGeneralAsociada = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaAdmision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FD = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nodo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Rama = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RXDS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenSOA = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Segmento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SNRDS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SNRUP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenPedido = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PuntosTecnicos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoCuenta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXUP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ÍnstalacionExpress = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TelefonoPrincipal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Telefonos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoEMTA = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CtaEspecial = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hub = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed27 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrdenPortabilidad = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Referido = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoCancelacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sistema = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubEstado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NoVTS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaveVendedor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MensalidadTotal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalCNR = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentoPrueba = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoFecha = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoTipoOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Revision = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CuentaFacturacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransferidoTrabajoTransacciones = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Equipo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Activo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AplicaTablet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConfirmacionInstalacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumOrden = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaveTecnicoPrincipal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tipo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tipo1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstadoAsignacionCredito = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed53 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumProgramaciones = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed55 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Estado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Compania = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Centro = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListaImpuestos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Direccion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Apellidos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nombre = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Prioridad = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumCuenta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Aprobado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AprobadoPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Moneda = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListaPrecios = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PorcientoDescuento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CompletadaPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MotivoReprogramacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnviadaPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UltimaModificacionPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UltimaModificacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comentarios = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreadoPor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Creado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Evento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaSolicitada = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Organizacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cerrado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Unnamed82 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CICPotencial = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_depuracionExportSiebelReserva1", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DepuracionExportSiebel1");

            migrationBuilder.DropTable(
                name: "depuracionExportSiebelCanceladas1");

            migrationBuilder.DropTable(
                name: "depuracionExportSiebelReserva1");
        }
    }
}
